// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rsbembodiments.proto

package asap.rsbembodiments;

public final class Rsbembodiments {
  private Rsbembodiments() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface JointOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string sid = 1;
    boolean hasSid();
    String getSid();
  }
  public static final class Joint extends
      com.google.protobuf.GeneratedMessage
      implements JointOrBuilder {
    // Use Joint.newBuilder() to construct.
    private Joint(Builder builder) {
      super(builder);
    }
    private Joint(boolean noInit) {}
    
    private static final Joint defaultInstance;
    public static Joint getDefaultInstance() {
      return defaultInstance;
    }
    
    public Joint getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return asap.rsbembodiments.Rsbembodiments.internal_static_asap_rsbembodiments_Joint_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return asap.rsbembodiments.Rsbembodiments.internal_static_asap_rsbembodiments_Joint_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string sid = 1;
    public static final int SID_FIELD_NUMBER = 1;
    private java.lang.Object sid_;
    public boolean hasSid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getSid() {
      java.lang.Object ref = sid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          sid_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getSidBytes() {
      java.lang.Object ref = sid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        sid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      sid_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasSid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getSidBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getSidBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static asap.rsbembodiments.Rsbembodiments.Joint parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static asap.rsbembodiments.Rsbembodiments.Joint parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static asap.rsbembodiments.Rsbembodiments.Joint parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static asap.rsbembodiments.Rsbembodiments.Joint parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static asap.rsbembodiments.Rsbembodiments.Joint parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static asap.rsbembodiments.Rsbembodiments.Joint parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static asap.rsbembodiments.Rsbembodiments.Joint parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static asap.rsbembodiments.Rsbembodiments.Joint parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static asap.rsbembodiments.Rsbembodiments.Joint parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static asap.rsbembodiments.Rsbembodiments.Joint parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(asap.rsbembodiments.Rsbembodiments.Joint prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements asap.rsbembodiments.Rsbembodiments.JointOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return asap.rsbembodiments.Rsbembodiments.internal_static_asap_rsbembodiments_Joint_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return asap.rsbembodiments.Rsbembodiments.internal_static_asap_rsbembodiments_Joint_fieldAccessorTable;
      }
      
      // Construct using asap.rsbembodiments.Rsbembodiments.Joint.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        sid_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return asap.rsbembodiments.Rsbembodiments.Joint.getDescriptor();
      }
      
      public asap.rsbembodiments.Rsbembodiments.Joint getDefaultInstanceForType() {
        return asap.rsbembodiments.Rsbembodiments.Joint.getDefaultInstance();
      }
      
      public asap.rsbembodiments.Rsbembodiments.Joint build() {
        asap.rsbembodiments.Rsbembodiments.Joint result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private asap.rsbembodiments.Rsbembodiments.Joint buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        asap.rsbembodiments.Rsbembodiments.Joint result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public asap.rsbembodiments.Rsbembodiments.Joint buildPartial() {
        asap.rsbembodiments.Rsbembodiments.Joint result = new asap.rsbembodiments.Rsbembodiments.Joint(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.sid_ = sid_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof asap.rsbembodiments.Rsbembodiments.Joint) {
          return mergeFrom((asap.rsbembodiments.Rsbembodiments.Joint)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(asap.rsbembodiments.Rsbembodiments.Joint other) {
        if (other == asap.rsbembodiments.Rsbembodiments.Joint.getDefaultInstance()) return this;
        if (other.hasSid()) {
          setSid(other.getSid());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasSid()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              sid_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string sid = 1;
      private java.lang.Object sid_ = "";
      public boolean hasSid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getSid() {
        java.lang.Object ref = sid_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          sid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setSid(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        sid_ = value;
        onChanged();
        return this;
      }
      public Builder clearSid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sid_ = getDefaultInstance().getSid();
        onChanged();
        return this;
      }
      void setSid(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        sid_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:asap.rsbembodiments.Joint)
    }
    
    static {
      defaultInstance = new Joint(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:asap.rsbembodiments.Joint)
  }
  
  public interface JointDataConfigReplyOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .asap.rsbembodiments.Joint joint = 1;
    java.util.List<asap.rsbembodiments.Rsbembodiments.Joint> 
        getJointList();
    asap.rsbembodiments.Rsbembodiments.Joint getJoint(int index);
    int getJointCount();
    java.util.List<? extends asap.rsbembodiments.Rsbembodiments.JointOrBuilder> 
        getJointOrBuilderList();
    asap.rsbembodiments.Rsbembodiments.JointOrBuilder getJointOrBuilder(
        int index);
  }
  public static final class JointDataConfigReply extends
      com.google.protobuf.GeneratedMessage
      implements JointDataConfigReplyOrBuilder {
    // Use JointDataConfigReply.newBuilder() to construct.
    private JointDataConfigReply(Builder builder) {
      super(builder);
    }
    private JointDataConfigReply(boolean noInit) {}
    
    private static final JointDataConfigReply defaultInstance;
    public static JointDataConfigReply getDefaultInstance() {
      return defaultInstance;
    }
    
    public JointDataConfigReply getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return asap.rsbembodiments.Rsbembodiments.internal_static_asap_rsbembodiments_JointDataConfigReply_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return asap.rsbembodiments.Rsbembodiments.internal_static_asap_rsbembodiments_JointDataConfigReply_fieldAccessorTable;
    }
    
    // repeated .asap.rsbembodiments.Joint joint = 1;
    public static final int JOINT_FIELD_NUMBER = 1;
    private java.util.List<asap.rsbembodiments.Rsbembodiments.Joint> joint_;
    public java.util.List<asap.rsbembodiments.Rsbembodiments.Joint> getJointList() {
      return joint_;
    }
    public java.util.List<? extends asap.rsbembodiments.Rsbembodiments.JointOrBuilder> 
        getJointOrBuilderList() {
      return joint_;
    }
    public int getJointCount() {
      return joint_.size();
    }
    public asap.rsbembodiments.Rsbembodiments.Joint getJoint(int index) {
      return joint_.get(index);
    }
    public asap.rsbembodiments.Rsbembodiments.JointOrBuilder getJointOrBuilder(
        int index) {
      return joint_.get(index);
    }
    
    private void initFields() {
      joint_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getJointCount(); i++) {
        if (!getJoint(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < joint_.size(); i++) {
        output.writeMessage(1, joint_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < joint_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, joint_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static asap.rsbembodiments.Rsbembodiments.JointDataConfigReply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static asap.rsbembodiments.Rsbembodiments.JointDataConfigReply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static asap.rsbembodiments.Rsbembodiments.JointDataConfigReply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static asap.rsbembodiments.Rsbembodiments.JointDataConfigReply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static asap.rsbembodiments.Rsbembodiments.JointDataConfigReply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static asap.rsbembodiments.Rsbembodiments.JointDataConfigReply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static asap.rsbembodiments.Rsbembodiments.JointDataConfigReply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static asap.rsbembodiments.Rsbembodiments.JointDataConfigReply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static asap.rsbembodiments.Rsbembodiments.JointDataConfigReply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static asap.rsbembodiments.Rsbembodiments.JointDataConfigReply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(asap.rsbembodiments.Rsbembodiments.JointDataConfigReply prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements asap.rsbembodiments.Rsbembodiments.JointDataConfigReplyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return asap.rsbembodiments.Rsbembodiments.internal_static_asap_rsbembodiments_JointDataConfigReply_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return asap.rsbembodiments.Rsbembodiments.internal_static_asap_rsbembodiments_JointDataConfigReply_fieldAccessorTable;
      }
      
      // Construct using asap.rsbembodiments.Rsbembodiments.JointDataConfigReply.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getJointFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (jointBuilder_ == null) {
          joint_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          jointBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return asap.rsbembodiments.Rsbembodiments.JointDataConfigReply.getDescriptor();
      }
      
      public asap.rsbembodiments.Rsbembodiments.JointDataConfigReply getDefaultInstanceForType() {
        return asap.rsbembodiments.Rsbembodiments.JointDataConfigReply.getDefaultInstance();
      }
      
      public asap.rsbembodiments.Rsbembodiments.JointDataConfigReply build() {
        asap.rsbembodiments.Rsbembodiments.JointDataConfigReply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private asap.rsbembodiments.Rsbembodiments.JointDataConfigReply buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        asap.rsbembodiments.Rsbembodiments.JointDataConfigReply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public asap.rsbembodiments.Rsbembodiments.JointDataConfigReply buildPartial() {
        asap.rsbembodiments.Rsbembodiments.JointDataConfigReply result = new asap.rsbembodiments.Rsbembodiments.JointDataConfigReply(this);
        int from_bitField0_ = bitField0_;
        if (jointBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            joint_ = java.util.Collections.unmodifiableList(joint_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.joint_ = joint_;
        } else {
          result.joint_ = jointBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof asap.rsbembodiments.Rsbembodiments.JointDataConfigReply) {
          return mergeFrom((asap.rsbembodiments.Rsbembodiments.JointDataConfigReply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(asap.rsbembodiments.Rsbembodiments.JointDataConfigReply other) {
        if (other == asap.rsbembodiments.Rsbembodiments.JointDataConfigReply.getDefaultInstance()) return this;
        if (jointBuilder_ == null) {
          if (!other.joint_.isEmpty()) {
            if (joint_.isEmpty()) {
              joint_ = other.joint_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureJointIsMutable();
              joint_.addAll(other.joint_);
            }
            onChanged();
          }
        } else {
          if (!other.joint_.isEmpty()) {
            if (jointBuilder_.isEmpty()) {
              jointBuilder_.dispose();
              jointBuilder_ = null;
              joint_ = other.joint_;
              bitField0_ = (bitField0_ & ~0x00000001);
              jointBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getJointFieldBuilder() : null;
            } else {
              jointBuilder_.addAllMessages(other.joint_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getJointCount(); i++) {
          if (!getJoint(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              asap.rsbembodiments.Rsbembodiments.Joint.Builder subBuilder = asap.rsbembodiments.Rsbembodiments.Joint.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addJoint(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .asap.rsbembodiments.Joint joint = 1;
      private java.util.List<asap.rsbembodiments.Rsbembodiments.Joint> joint_ =
        java.util.Collections.emptyList();
      private void ensureJointIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          joint_ = new java.util.ArrayList<asap.rsbembodiments.Rsbembodiments.Joint>(joint_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          asap.rsbembodiments.Rsbembodiments.Joint, asap.rsbembodiments.Rsbembodiments.Joint.Builder, asap.rsbembodiments.Rsbembodiments.JointOrBuilder> jointBuilder_;
      
      public java.util.List<asap.rsbembodiments.Rsbembodiments.Joint> getJointList() {
        if (jointBuilder_ == null) {
          return java.util.Collections.unmodifiableList(joint_);
        } else {
          return jointBuilder_.getMessageList();
        }
      }
      public int getJointCount() {
        if (jointBuilder_ == null) {
          return joint_.size();
        } else {
          return jointBuilder_.getCount();
        }
      }
      public asap.rsbembodiments.Rsbembodiments.Joint getJoint(int index) {
        if (jointBuilder_ == null) {
          return joint_.get(index);
        } else {
          return jointBuilder_.getMessage(index);
        }
      }
      public Builder setJoint(
          int index, asap.rsbembodiments.Rsbembodiments.Joint value) {
        if (jointBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureJointIsMutable();
          joint_.set(index, value);
          onChanged();
        } else {
          jointBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setJoint(
          int index, asap.rsbembodiments.Rsbembodiments.Joint.Builder builderForValue) {
        if (jointBuilder_ == null) {
          ensureJointIsMutable();
          joint_.set(index, builderForValue.build());
          onChanged();
        } else {
          jointBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addJoint(asap.rsbembodiments.Rsbembodiments.Joint value) {
        if (jointBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureJointIsMutable();
          joint_.add(value);
          onChanged();
        } else {
          jointBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addJoint(
          int index, asap.rsbembodiments.Rsbembodiments.Joint value) {
        if (jointBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureJointIsMutable();
          joint_.add(index, value);
          onChanged();
        } else {
          jointBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addJoint(
          asap.rsbembodiments.Rsbembodiments.Joint.Builder builderForValue) {
        if (jointBuilder_ == null) {
          ensureJointIsMutable();
          joint_.add(builderForValue.build());
          onChanged();
        } else {
          jointBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addJoint(
          int index, asap.rsbembodiments.Rsbembodiments.Joint.Builder builderForValue) {
        if (jointBuilder_ == null) {
          ensureJointIsMutable();
          joint_.add(index, builderForValue.build());
          onChanged();
        } else {
          jointBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllJoint(
          java.lang.Iterable<? extends asap.rsbembodiments.Rsbembodiments.Joint> values) {
        if (jointBuilder_ == null) {
          ensureJointIsMutable();
          super.addAll(values, joint_);
          onChanged();
        } else {
          jointBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearJoint() {
        if (jointBuilder_ == null) {
          joint_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          jointBuilder_.clear();
        }
        return this;
      }
      public Builder removeJoint(int index) {
        if (jointBuilder_ == null) {
          ensureJointIsMutable();
          joint_.remove(index);
          onChanged();
        } else {
          jointBuilder_.remove(index);
        }
        return this;
      }
      public asap.rsbembodiments.Rsbembodiments.Joint.Builder getJointBuilder(
          int index) {
        return getJointFieldBuilder().getBuilder(index);
      }
      public asap.rsbembodiments.Rsbembodiments.JointOrBuilder getJointOrBuilder(
          int index) {
        if (jointBuilder_ == null) {
          return joint_.get(index);  } else {
          return jointBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends asap.rsbembodiments.Rsbembodiments.JointOrBuilder> 
           getJointOrBuilderList() {
        if (jointBuilder_ != null) {
          return jointBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(joint_);
        }
      }
      public asap.rsbembodiments.Rsbembodiments.Joint.Builder addJointBuilder() {
        return getJointFieldBuilder().addBuilder(
            asap.rsbembodiments.Rsbembodiments.Joint.getDefaultInstance());
      }
      public asap.rsbembodiments.Rsbembodiments.Joint.Builder addJointBuilder(
          int index) {
        return getJointFieldBuilder().addBuilder(
            index, asap.rsbembodiments.Rsbembodiments.Joint.getDefaultInstance());
      }
      public java.util.List<asap.rsbembodiments.Rsbembodiments.Joint.Builder> 
           getJointBuilderList() {
        return getJointFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          asap.rsbembodiments.Rsbembodiments.Joint, asap.rsbembodiments.Rsbembodiments.Joint.Builder, asap.rsbembodiments.Rsbembodiments.JointOrBuilder> 
          getJointFieldBuilder() {
        if (jointBuilder_ == null) {
          jointBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              asap.rsbembodiments.Rsbembodiments.Joint, asap.rsbembodiments.Rsbembodiments.Joint.Builder, asap.rsbembodiments.Rsbembodiments.JointOrBuilder>(
                  joint_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          joint_ = null;
        }
        return jointBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:asap.rsbembodiments.JointDataConfigReply)
    }
    
    static {
      defaultInstance = new JointDataConfigReply(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:asap.rsbembodiments.JointDataConfigReply)
  }
  
  public interface JointDataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated float data = 1 [packed = true];
    java.util.List<java.lang.Float> getDataList();
    int getDataCount();
    float getData(int index);
  }
  public static final class JointData extends
      com.google.protobuf.GeneratedMessage
      implements JointDataOrBuilder {
    // Use JointData.newBuilder() to construct.
    private JointData(Builder builder) {
      super(builder);
    }
    private JointData(boolean noInit) {}
    
    private static final JointData defaultInstance;
    public static JointData getDefaultInstance() {
      return defaultInstance;
    }
    
    public JointData getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return asap.rsbembodiments.Rsbembodiments.internal_static_asap_rsbembodiments_JointData_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return asap.rsbembodiments.Rsbembodiments.internal_static_asap_rsbembodiments_JointData_fieldAccessorTable;
    }
    
    // repeated float data = 1 [packed = true];
    public static final int DATA_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Float> data_;
    public java.util.List<java.lang.Float>
        getDataList() {
      return data_;
    }
    public int getDataCount() {
      return data_.size();
    }
    public float getData(int index) {
      return data_.get(index);
    }
    private int dataMemoizedSerializedSize = -1;
    
    private void initFields() {
      data_ = java.util.Collections.emptyList();;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getDataList().size() > 0) {
        output.writeRawVarint32(10);
        output.writeRawVarint32(dataMemoizedSerializedSize);
      }
      for (int i = 0; i < data_.size(); i++) {
        output.writeFloatNoTag(data_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      {
        int dataSize = 0;
        dataSize = 4 * getDataList().size();
        size += dataSize;
        if (!getDataList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        dataMemoizedSerializedSize = dataSize;
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static asap.rsbembodiments.Rsbembodiments.JointData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static asap.rsbembodiments.Rsbembodiments.JointData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static asap.rsbembodiments.Rsbembodiments.JointData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static asap.rsbembodiments.Rsbembodiments.JointData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static asap.rsbembodiments.Rsbembodiments.JointData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static asap.rsbembodiments.Rsbembodiments.JointData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static asap.rsbembodiments.Rsbembodiments.JointData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static asap.rsbembodiments.Rsbembodiments.JointData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static asap.rsbembodiments.Rsbembodiments.JointData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static asap.rsbembodiments.Rsbembodiments.JointData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(asap.rsbembodiments.Rsbembodiments.JointData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements asap.rsbembodiments.Rsbembodiments.JointDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return asap.rsbembodiments.Rsbembodiments.internal_static_asap_rsbembodiments_JointData_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return asap.rsbembodiments.Rsbembodiments.internal_static_asap_rsbembodiments_JointData_fieldAccessorTable;
      }
      
      // Construct using asap.rsbembodiments.Rsbembodiments.JointData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        data_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return asap.rsbembodiments.Rsbembodiments.JointData.getDescriptor();
      }
      
      public asap.rsbembodiments.Rsbembodiments.JointData getDefaultInstanceForType() {
        return asap.rsbembodiments.Rsbembodiments.JointData.getDefaultInstance();
      }
      
      public asap.rsbembodiments.Rsbembodiments.JointData build() {
        asap.rsbembodiments.Rsbembodiments.JointData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private asap.rsbembodiments.Rsbembodiments.JointData buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        asap.rsbembodiments.Rsbembodiments.JointData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public asap.rsbembodiments.Rsbembodiments.JointData buildPartial() {
        asap.rsbembodiments.Rsbembodiments.JointData result = new asap.rsbembodiments.Rsbembodiments.JointData(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          data_ = java.util.Collections.unmodifiableList(data_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.data_ = data_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof asap.rsbembodiments.Rsbembodiments.JointData) {
          return mergeFrom((asap.rsbembodiments.Rsbembodiments.JointData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(asap.rsbembodiments.Rsbembodiments.JointData other) {
        if (other == asap.rsbembodiments.Rsbembodiments.JointData.getDefaultInstance()) return this;
        if (!other.data_.isEmpty()) {
          if (data_.isEmpty()) {
            data_ = other.data_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureDataIsMutable();
            data_.addAll(other.data_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 13: {
              ensureDataIsMutable();
              data_.add(input.readFloat());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              while (input.getBytesUntilLimit() > 0) {
                addData(input.readFloat());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated float data = 1 [packed = true];
      private java.util.List<java.lang.Float> data_ = java.util.Collections.emptyList();;
      private void ensureDataIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          data_ = new java.util.ArrayList<java.lang.Float>(data_);
          bitField0_ |= 0x00000001;
         }
      }
      public java.util.List<java.lang.Float>
          getDataList() {
        return java.util.Collections.unmodifiableList(data_);
      }
      public int getDataCount() {
        return data_.size();
      }
      public float getData(int index) {
        return data_.get(index);
      }
      public Builder setData(
          int index, float value) {
        ensureDataIsMutable();
        data_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addData(float value) {
        ensureDataIsMutable();
        data_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllData(
          java.lang.Iterable<? extends java.lang.Float> values) {
        ensureDataIsMutable();
        super.addAll(values, data_);
        onChanged();
        return this;
      }
      public Builder clearData() {
        data_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:asap.rsbembodiments.JointData)
    }
    
    static {
      defaultInstance = new JointData(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:asap.rsbembodiments.JointData)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_asap_rsbembodiments_Joint_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_asap_rsbembodiments_Joint_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_asap_rsbembodiments_JointDataConfigReply_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_asap_rsbembodiments_JointDataConfigReply_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_asap_rsbembodiments_JointData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_asap_rsbembodiments_JointData_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024rsbembodiments.proto\022\023asap.rsbembodime" +
      "nts\"\024\n\005Joint\022\013\n\003sid\030\001 \002(\t\"A\n\024JointDataCo" +
      "nfigReply\022)\n\005joint\030\001 \003(\0132\032.asap.rsbembod" +
      "iments.Joint\"\035\n\tJointData\022\020\n\004data\030\001 \003(\002B" +
      "\002\020\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_asap_rsbembodiments_Joint_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_asap_rsbembodiments_Joint_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_asap_rsbembodiments_Joint_descriptor,
              new java.lang.String[] { "Sid", },
              asap.rsbembodiments.Rsbembodiments.Joint.class,
              asap.rsbembodiments.Rsbembodiments.Joint.Builder.class);
          internal_static_asap_rsbembodiments_JointDataConfigReply_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_asap_rsbembodiments_JointDataConfigReply_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_asap_rsbembodiments_JointDataConfigReply_descriptor,
              new java.lang.String[] { "Joint", },
              asap.rsbembodiments.Rsbembodiments.JointDataConfigReply.class,
              asap.rsbembodiments.Rsbembodiments.JointDataConfigReply.Builder.class);
          internal_static_asap_rsbembodiments_JointData_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_asap_rsbembodiments_JointData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_asap_rsbembodiments_JointData_descriptor,
              new java.lang.String[] { "Data", },
              asap.rsbembodiments.Rsbembodiments.JointData.class,
              asap.rsbembodiments.Rsbembodiments.JointData.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
