// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rsbworldenvironment.proto

package asap.rsbworldenvironment;

public final class Rsbworldenvironment {
  private Rsbworldenvironment() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RSBWorldObjectOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string objectId = 1;
    /**
     * <code>required string objectId = 1;</code>
     */
    boolean hasObjectId();
    /**
     * <code>required string objectId = 1;</code>
     */
    java.lang.String getObjectId();
    /**
     * <code>required string objectId = 1;</code>
     */
    com.google.protobuf.ByteString
        getObjectIdBytes();

    // repeated float position = 2 [packed = true];
    /**
     * <code>repeated float position = 2 [packed = true];</code>
     */
    java.util.List<java.lang.Float> getPositionList();
    /**
     * <code>repeated float position = 2 [packed = true];</code>
     */
    int getPositionCount();
    /**
     * <code>repeated float position = 2 [packed = true];</code>
     */
    float getPosition(int index);
  }
  /**
   * Protobuf type {@code asap.rsbworldenvironment.RSBWorldObject}
   */
  public static final class RSBWorldObject extends
      com.google.protobuf.GeneratedMessage
      implements RSBWorldObjectOrBuilder {
    // Use RSBWorldObject.newBuilder() to construct.
    private RSBWorldObject(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RSBWorldObject(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RSBWorldObject defaultInstance;
    public static RSBWorldObject getDefaultInstance() {
      return defaultInstance;
    }

    public RSBWorldObject getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RSBWorldObject(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              objectId_ = input.readBytes();
              break;
            }
            case 21: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                position_ = new java.util.ArrayList<java.lang.Float>();
                mutable_bitField0_ |= 0x00000002;
              }
              position_.add(input.readFloat());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
                position_ = new java.util.ArrayList<java.lang.Float>();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                position_.add(input.readFloat());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          position_ = java.util.Collections.unmodifiableList(position_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return asap.rsbworldenvironment.Rsbworldenvironment.internal_static_asap_rsbworldenvironment_RSBWorldObject_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return asap.rsbworldenvironment.Rsbworldenvironment.internal_static_asap_rsbworldenvironment_RSBWorldObject_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObject.class, asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObject.Builder.class);
    }

    public static com.google.protobuf.Parser<RSBWorldObject> PARSER =
        new com.google.protobuf.AbstractParser<RSBWorldObject>() {
      public RSBWorldObject parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RSBWorldObject(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RSBWorldObject> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string objectId = 1;
    public static final int OBJECTID_FIELD_NUMBER = 1;
    private java.lang.Object objectId_;
    /**
     * <code>required string objectId = 1;</code>
     */
    public boolean hasObjectId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string objectId = 1;</code>
     */
    public java.lang.String getObjectId() {
      java.lang.Object ref = objectId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          objectId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string objectId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getObjectIdBytes() {
      java.lang.Object ref = objectId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        objectId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated float position = 2 [packed = true];
    public static final int POSITION_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Float> position_;
    /**
     * <code>repeated float position = 2 [packed = true];</code>
     */
    public java.util.List<java.lang.Float>
        getPositionList() {
      return position_;
    }
    /**
     * <code>repeated float position = 2 [packed = true];</code>
     */
    public int getPositionCount() {
      return position_.size();
    }
    /**
     * <code>repeated float position = 2 [packed = true];</code>
     */
    public float getPosition(int index) {
      return position_.get(index);
    }
    private int positionMemoizedSerializedSize = -1;

    private void initFields() {
      objectId_ = "";
      position_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasObjectId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getObjectIdBytes());
      }
      if (getPositionList().size() > 0) {
        output.writeRawVarint32(18);
        output.writeRawVarint32(positionMemoizedSerializedSize);
      }
      for (int i = 0; i < position_.size(); i++) {
        output.writeFloatNoTag(position_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getObjectIdBytes());
      }
      {
        int dataSize = 0;
        dataSize = 4 * getPositionList().size();
        size += dataSize;
        if (!getPositionList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        positionMemoizedSerializedSize = dataSize;
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObject parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObject parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObject parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObject parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObject parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObject parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObject parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObject parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObject parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObject parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObject prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code asap.rsbworldenvironment.RSBWorldObject}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObjectOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return asap.rsbworldenvironment.Rsbworldenvironment.internal_static_asap_rsbworldenvironment_RSBWorldObject_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return asap.rsbworldenvironment.Rsbworldenvironment.internal_static_asap_rsbworldenvironment_RSBWorldObject_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObject.class, asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObject.Builder.class);
      }

      // Construct using asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObject.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        objectId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        position_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return asap.rsbworldenvironment.Rsbworldenvironment.internal_static_asap_rsbworldenvironment_RSBWorldObject_descriptor;
      }

      public asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObject getDefaultInstanceForType() {
        return asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObject.getDefaultInstance();
      }

      public asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObject build() {
        asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObject result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObject buildPartial() {
        asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObject result = new asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObject(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.objectId_ = objectId_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          position_ = java.util.Collections.unmodifiableList(position_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.position_ = position_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObject) {
          return mergeFrom((asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObject)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObject other) {
        if (other == asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObject.getDefaultInstance()) return this;
        if (other.hasObjectId()) {
          bitField0_ |= 0x00000001;
          objectId_ = other.objectId_;
          onChanged();
        }
        if (!other.position_.isEmpty()) {
          if (position_.isEmpty()) {
            position_ = other.position_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensurePositionIsMutable();
            position_.addAll(other.position_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasObjectId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObject parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObject) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string objectId = 1;
      private java.lang.Object objectId_ = "";
      /**
       * <code>required string objectId = 1;</code>
       */
      public boolean hasObjectId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string objectId = 1;</code>
       */
      public java.lang.String getObjectId() {
        java.lang.Object ref = objectId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          objectId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string objectId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getObjectIdBytes() {
        java.lang.Object ref = objectId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          objectId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string objectId = 1;</code>
       */
      public Builder setObjectId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        objectId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string objectId = 1;</code>
       */
      public Builder clearObjectId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        objectId_ = getDefaultInstance().getObjectId();
        onChanged();
        return this;
      }
      /**
       * <code>required string objectId = 1;</code>
       */
      public Builder setObjectIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        objectId_ = value;
        onChanged();
        return this;
      }

      // repeated float position = 2 [packed = true];
      private java.util.List<java.lang.Float> position_ = java.util.Collections.emptyList();
      private void ensurePositionIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          position_ = new java.util.ArrayList<java.lang.Float>(position_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated float position = 2 [packed = true];</code>
       */
      public java.util.List<java.lang.Float>
          getPositionList() {
        return java.util.Collections.unmodifiableList(position_);
      }
      /**
       * <code>repeated float position = 2 [packed = true];</code>
       */
      public int getPositionCount() {
        return position_.size();
      }
      /**
       * <code>repeated float position = 2 [packed = true];</code>
       */
      public float getPosition(int index) {
        return position_.get(index);
      }
      /**
       * <code>repeated float position = 2 [packed = true];</code>
       */
      public Builder setPosition(
          int index, float value) {
        ensurePositionIsMutable();
        position_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float position = 2 [packed = true];</code>
       */
      public Builder addPosition(float value) {
        ensurePositionIsMutable();
        position_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float position = 2 [packed = true];</code>
       */
      public Builder addAllPosition(
          java.lang.Iterable<? extends java.lang.Float> values) {
        ensurePositionIsMutable();
        super.addAll(values, position_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float position = 2 [packed = true];</code>
       */
      public Builder clearPosition() {
        position_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:asap.rsbworldenvironment.RSBWorldObject)
    }

    static {
      defaultInstance = new RSBWorldObject(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:asap.rsbworldenvironment.RSBWorldObject)
  }

  public interface RSBWorldObjectsOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .asap.rsbworldenvironment.RSBWorldObject worldObjects = 1;
    /**
     * <code>repeated .asap.rsbworldenvironment.RSBWorldObject worldObjects = 1;</code>
     */
    java.util.List<asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObject> 
        getWorldObjectsList();
    /**
     * <code>repeated .asap.rsbworldenvironment.RSBWorldObject worldObjects = 1;</code>
     */
    asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObject getWorldObjects(int index);
    /**
     * <code>repeated .asap.rsbworldenvironment.RSBWorldObject worldObjects = 1;</code>
     */
    int getWorldObjectsCount();
    /**
     * <code>repeated .asap.rsbworldenvironment.RSBWorldObject worldObjects = 1;</code>
     */
    java.util.List<? extends asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObjectOrBuilder> 
        getWorldObjectsOrBuilderList();
    /**
     * <code>repeated .asap.rsbworldenvironment.RSBWorldObject worldObjects = 1;</code>
     */
    asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObjectOrBuilder getWorldObjectsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code asap.rsbworldenvironment.RSBWorldObjects}
   */
  public static final class RSBWorldObjects extends
      com.google.protobuf.GeneratedMessage
      implements RSBWorldObjectsOrBuilder {
    // Use RSBWorldObjects.newBuilder() to construct.
    private RSBWorldObjects(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RSBWorldObjects(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RSBWorldObjects defaultInstance;
    public static RSBWorldObjects getDefaultInstance() {
      return defaultInstance;
    }

    public RSBWorldObjects getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RSBWorldObjects(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                worldObjects_ = new java.util.ArrayList<asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObject>();
                mutable_bitField0_ |= 0x00000001;
              }
              worldObjects_.add(input.readMessage(asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObject.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          worldObjects_ = java.util.Collections.unmodifiableList(worldObjects_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return asap.rsbworldenvironment.Rsbworldenvironment.internal_static_asap_rsbworldenvironment_RSBWorldObjects_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return asap.rsbworldenvironment.Rsbworldenvironment.internal_static_asap_rsbworldenvironment_RSBWorldObjects_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObjects.class, asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObjects.Builder.class);
    }

    public static com.google.protobuf.Parser<RSBWorldObjects> PARSER =
        new com.google.protobuf.AbstractParser<RSBWorldObjects>() {
      public RSBWorldObjects parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RSBWorldObjects(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RSBWorldObjects> getParserForType() {
      return PARSER;
    }

    // repeated .asap.rsbworldenvironment.RSBWorldObject worldObjects = 1;
    public static final int WORLDOBJECTS_FIELD_NUMBER = 1;
    private java.util.List<asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObject> worldObjects_;
    /**
     * <code>repeated .asap.rsbworldenvironment.RSBWorldObject worldObjects = 1;</code>
     */
    public java.util.List<asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObject> getWorldObjectsList() {
      return worldObjects_;
    }
    /**
     * <code>repeated .asap.rsbworldenvironment.RSBWorldObject worldObjects = 1;</code>
     */
    public java.util.List<? extends asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObjectOrBuilder> 
        getWorldObjectsOrBuilderList() {
      return worldObjects_;
    }
    /**
     * <code>repeated .asap.rsbworldenvironment.RSBWorldObject worldObjects = 1;</code>
     */
    public int getWorldObjectsCount() {
      return worldObjects_.size();
    }
    /**
     * <code>repeated .asap.rsbworldenvironment.RSBWorldObject worldObjects = 1;</code>
     */
    public asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObject getWorldObjects(int index) {
      return worldObjects_.get(index);
    }
    /**
     * <code>repeated .asap.rsbworldenvironment.RSBWorldObject worldObjects = 1;</code>
     */
    public asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObjectOrBuilder getWorldObjectsOrBuilder(
        int index) {
      return worldObjects_.get(index);
    }

    private void initFields() {
      worldObjects_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getWorldObjectsCount(); i++) {
        if (!getWorldObjects(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < worldObjects_.size(); i++) {
        output.writeMessage(1, worldObjects_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < worldObjects_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, worldObjects_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObjects parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObjects parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObjects parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObjects parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObjects parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObjects parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObjects parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObjects parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObjects parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObjects parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObjects prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code asap.rsbworldenvironment.RSBWorldObjects}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObjectsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return asap.rsbworldenvironment.Rsbworldenvironment.internal_static_asap_rsbworldenvironment_RSBWorldObjects_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return asap.rsbworldenvironment.Rsbworldenvironment.internal_static_asap_rsbworldenvironment_RSBWorldObjects_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObjects.class, asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObjects.Builder.class);
      }

      // Construct using asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObjects.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getWorldObjectsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (worldObjectsBuilder_ == null) {
          worldObjects_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          worldObjectsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return asap.rsbworldenvironment.Rsbworldenvironment.internal_static_asap_rsbworldenvironment_RSBWorldObjects_descriptor;
      }

      public asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObjects getDefaultInstanceForType() {
        return asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObjects.getDefaultInstance();
      }

      public asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObjects build() {
        asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObjects result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObjects buildPartial() {
        asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObjects result = new asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObjects(this);
        int from_bitField0_ = bitField0_;
        if (worldObjectsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            worldObjects_ = java.util.Collections.unmodifiableList(worldObjects_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.worldObjects_ = worldObjects_;
        } else {
          result.worldObjects_ = worldObjectsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObjects) {
          return mergeFrom((asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObjects)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObjects other) {
        if (other == asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObjects.getDefaultInstance()) return this;
        if (worldObjectsBuilder_ == null) {
          if (!other.worldObjects_.isEmpty()) {
            if (worldObjects_.isEmpty()) {
              worldObjects_ = other.worldObjects_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureWorldObjectsIsMutable();
              worldObjects_.addAll(other.worldObjects_);
            }
            onChanged();
          }
        } else {
          if (!other.worldObjects_.isEmpty()) {
            if (worldObjectsBuilder_.isEmpty()) {
              worldObjectsBuilder_.dispose();
              worldObjectsBuilder_ = null;
              worldObjects_ = other.worldObjects_;
              bitField0_ = (bitField0_ & ~0x00000001);
              worldObjectsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getWorldObjectsFieldBuilder() : null;
            } else {
              worldObjectsBuilder_.addAllMessages(other.worldObjects_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getWorldObjectsCount(); i++) {
          if (!getWorldObjects(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObjects parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObjects) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .asap.rsbworldenvironment.RSBWorldObject worldObjects = 1;
      private java.util.List<asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObject> worldObjects_ =
        java.util.Collections.emptyList();
      private void ensureWorldObjectsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          worldObjects_ = new java.util.ArrayList<asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObject>(worldObjects_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObject, asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObject.Builder, asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObjectOrBuilder> worldObjectsBuilder_;

      /**
       * <code>repeated .asap.rsbworldenvironment.RSBWorldObject worldObjects = 1;</code>
       */
      public java.util.List<asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObject> getWorldObjectsList() {
        if (worldObjectsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(worldObjects_);
        } else {
          return worldObjectsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .asap.rsbworldenvironment.RSBWorldObject worldObjects = 1;</code>
       */
      public int getWorldObjectsCount() {
        if (worldObjectsBuilder_ == null) {
          return worldObjects_.size();
        } else {
          return worldObjectsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .asap.rsbworldenvironment.RSBWorldObject worldObjects = 1;</code>
       */
      public asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObject getWorldObjects(int index) {
        if (worldObjectsBuilder_ == null) {
          return worldObjects_.get(index);
        } else {
          return worldObjectsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .asap.rsbworldenvironment.RSBWorldObject worldObjects = 1;</code>
       */
      public Builder setWorldObjects(
          int index, asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObject value) {
        if (worldObjectsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureWorldObjectsIsMutable();
          worldObjects_.set(index, value);
          onChanged();
        } else {
          worldObjectsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .asap.rsbworldenvironment.RSBWorldObject worldObjects = 1;</code>
       */
      public Builder setWorldObjects(
          int index, asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObject.Builder builderForValue) {
        if (worldObjectsBuilder_ == null) {
          ensureWorldObjectsIsMutable();
          worldObjects_.set(index, builderForValue.build());
          onChanged();
        } else {
          worldObjectsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .asap.rsbworldenvironment.RSBWorldObject worldObjects = 1;</code>
       */
      public Builder addWorldObjects(asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObject value) {
        if (worldObjectsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureWorldObjectsIsMutable();
          worldObjects_.add(value);
          onChanged();
        } else {
          worldObjectsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .asap.rsbworldenvironment.RSBWorldObject worldObjects = 1;</code>
       */
      public Builder addWorldObjects(
          int index, asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObject value) {
        if (worldObjectsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureWorldObjectsIsMutable();
          worldObjects_.add(index, value);
          onChanged();
        } else {
          worldObjectsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .asap.rsbworldenvironment.RSBWorldObject worldObjects = 1;</code>
       */
      public Builder addWorldObjects(
          asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObject.Builder builderForValue) {
        if (worldObjectsBuilder_ == null) {
          ensureWorldObjectsIsMutable();
          worldObjects_.add(builderForValue.build());
          onChanged();
        } else {
          worldObjectsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .asap.rsbworldenvironment.RSBWorldObject worldObjects = 1;</code>
       */
      public Builder addWorldObjects(
          int index, asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObject.Builder builderForValue) {
        if (worldObjectsBuilder_ == null) {
          ensureWorldObjectsIsMutable();
          worldObjects_.add(index, builderForValue.build());
          onChanged();
        } else {
          worldObjectsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .asap.rsbworldenvironment.RSBWorldObject worldObjects = 1;</code>
       */
      public Builder addAllWorldObjects(
          java.lang.Iterable<? extends asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObject> values) {
        if (worldObjectsBuilder_ == null) {
          ensureWorldObjectsIsMutable();
          super.addAll(values, worldObjects_);
          onChanged();
        } else {
          worldObjectsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .asap.rsbworldenvironment.RSBWorldObject worldObjects = 1;</code>
       */
      public Builder clearWorldObjects() {
        if (worldObjectsBuilder_ == null) {
          worldObjects_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          worldObjectsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .asap.rsbworldenvironment.RSBWorldObject worldObjects = 1;</code>
       */
      public Builder removeWorldObjects(int index) {
        if (worldObjectsBuilder_ == null) {
          ensureWorldObjectsIsMutable();
          worldObjects_.remove(index);
          onChanged();
        } else {
          worldObjectsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .asap.rsbworldenvironment.RSBWorldObject worldObjects = 1;</code>
       */
      public asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObject.Builder getWorldObjectsBuilder(
          int index) {
        return getWorldObjectsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .asap.rsbworldenvironment.RSBWorldObject worldObjects = 1;</code>
       */
      public asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObjectOrBuilder getWorldObjectsOrBuilder(
          int index) {
        if (worldObjectsBuilder_ == null) {
          return worldObjects_.get(index);  } else {
          return worldObjectsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .asap.rsbworldenvironment.RSBWorldObject worldObjects = 1;</code>
       */
      public java.util.List<? extends asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObjectOrBuilder> 
           getWorldObjectsOrBuilderList() {
        if (worldObjectsBuilder_ != null) {
          return worldObjectsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(worldObjects_);
        }
      }
      /**
       * <code>repeated .asap.rsbworldenvironment.RSBWorldObject worldObjects = 1;</code>
       */
      public asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObject.Builder addWorldObjectsBuilder() {
        return getWorldObjectsFieldBuilder().addBuilder(
            asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObject.getDefaultInstance());
      }
      /**
       * <code>repeated .asap.rsbworldenvironment.RSBWorldObject worldObjects = 1;</code>
       */
      public asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObject.Builder addWorldObjectsBuilder(
          int index) {
        return getWorldObjectsFieldBuilder().addBuilder(
            index, asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObject.getDefaultInstance());
      }
      /**
       * <code>repeated .asap.rsbworldenvironment.RSBWorldObject worldObjects = 1;</code>
       */
      public java.util.List<asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObject.Builder> 
           getWorldObjectsBuilderList() {
        return getWorldObjectsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObject, asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObject.Builder, asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObjectOrBuilder> 
          getWorldObjectsFieldBuilder() {
        if (worldObjectsBuilder_ == null) {
          worldObjectsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObject, asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObject.Builder, asap.rsbworldenvironment.Rsbworldenvironment.RSBWorldObjectOrBuilder>(
                  worldObjects_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          worldObjects_ = null;
        }
        return worldObjectsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:asap.rsbworldenvironment.RSBWorldObjects)
    }

    static {
      defaultInstance = new RSBWorldObjects(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:asap.rsbworldenvironment.RSBWorldObjects)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_asap_rsbworldenvironment_RSBWorldObject_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_asap_rsbworldenvironment_RSBWorldObject_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_asap_rsbworldenvironment_RSBWorldObjects_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_asap_rsbworldenvironment_RSBWorldObjects_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031rsbworldenvironment.proto\022\030asap.rsbwor" +
      "ldenvironment\"8\n\016RSBWorldObject\022\020\n\010objec" +
      "tId\030\001 \002(\t\022\024\n\010position\030\002 \003(\002B\002\020\001\"Q\n\017RSBWo" +
      "rldObjects\022>\n\014worldObjects\030\001 \003(\0132(.asap." +
      "rsbworldenvironment.RSBWorldObject"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_asap_rsbworldenvironment_RSBWorldObject_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_asap_rsbworldenvironment_RSBWorldObject_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_asap_rsbworldenvironment_RSBWorldObject_descriptor,
              new java.lang.String[] { "ObjectId", "Position", });
          internal_static_asap_rsbworldenvironment_RSBWorldObjects_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_asap_rsbworldenvironment_RSBWorldObjects_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_asap_rsbworldenvironment_RSBWorldObjects_descriptor,
              new java.lang.String[] { "WorldObjects", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
